name = "RBM_Hidden_Unit_Importance"
uuid = "18c5b9ad-20a6-4587-bcd1-d3f661342d19"
authors = ["JFdCD <j.cossio.diaz@gmail.com>"]
version = "1.0.3"

[deps]
LogStatFunctions = "1b3c2205-da69-4893-b2df-717075b12251"
RestrictedBoltzmannMachines = "12e6b396-7db5-4506-8cb6-664a4fe1e50e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.9"
LogStatFunctions = "1"
RestrictedBoltzmannMachines = "3"
Statistics = "1"